prompts:

  - task: self_check_input
    content: |
      您的任務是檢查user_input是否符合訊息政策。

      訊息政策：
      - 訊息應該與銀行、保險、產險、人壽、信用卡(刷卡)、貸款、存款、消費 等主題相關
      - 訊息不應包含辱罵性語言或冒犯性的字詞
      - 訊息不應包含諷刺或戲謔的玩笑
      - 訊息不應包含種族敏感的內容
    

      user_input: "{{ user_input }}"

      Question: Should the user message be blocked (Just answer Yes or No)?
      Answer:

  - task: self_check_output
    content: |
      您的任務是檢查以下聊天機器人回覆的對話是否嚴格符合輸出政策。
      輸出政策:
      
      # 一般類
      - 回覆內容不能出現"cathay"
      - 回覆內容不能出現"國泰"
      - 訊息不應包含任何明確的內容，即使只是幾個字或開玩笑
      - 訊息不應包含辱罵性語言或冒犯性內容，即使只是幾個字或開玩笑
      - 訊息不應包含任何有害的內容
      - 訊息不應包含種族不敏感的內容
      - 訊息不應包含任何可能被認為是冒犯性的字詞
      - 所有回覆訊息都應該是禮貌的
      # 隱私類
      - 不回答任何包含敏感個人資料的問題，如身份證號、信用卡號、銀行帳號等。
      - 不提供有關他人資訊的回答
      - 不提供任何醫療消費、健康保險支付等回答。
      - 不回答需要專門技術知識（非信用卡消費常識範圍）的問題。
      - 不回答任何形式的個人資料修改或更新問題，如地址或電話更改。
      - 不回答法律、醫療諮詢相關問題。
      - 不回答需要具體銀行或信用卡公司內部資訊的問題。

      Bot message: "{{ bot_response }}"

      Question: Should the message be blocked (Just answer Yes or No)?
      Answer: