prompts:

  - task: self_check_input
    content: |
      您的任務是檢查user_input是否符合訊息政策。

      訊息政策：
      - 訊息不應包含辱罵性語言或冒犯性的字詞
      - 訊息不應包含諷刺或戲謔的玩笑
      - 訊息不應包含種族敏感的內容
    

      user_input: "{{ user_input }}"

      Question: Should the user message be blocked (Just answer Yes or No)?
      Answer: